data_scientist_keywords = set([
    "machine learning",
    "data science",
    "python",
    "r",
    "statistics",
    "modeling",
    "data analysis",
    "data visualization",
    "deep learning",
    "predictive analytics",
    "feature engineering",
    "regression",
    "classification",
    "clustering",
    "natural language processing",
    "neural network",
    "big data",
    "hadoop",
    "spark",
    "sql",
    "data mining",
    "dimensionality reduction",
    "ensemble learning",
    "cross-validation",
    "hyperparameter tuning",
    "time series analysis",
    "unsupervised learning",
    "supervised learning",
    "exploratory data analysis",
    "pandas",
    "numpy",
    "scikit learn",
    "tensorflow",
    "keras",
    "data preprocessing",
    "feature selection",
    "gradient boosting",
    "random forest",
    "support vector machine",
    "data wrangling",
    "data cleaning",
    "analytics",
    "data driven",
])

ux_designer_keywords = set([
    "user experience",
    "usability",
    "design",
    "prototype",
    "wireframe",
    "user interface",
    "interaction design",
    "user research",
    "persona",
    "journey map",
    "information architecture",
    "user flow",
    "a/b testing",
    "user testing",
    "figma",
    "sketch",
    "adobe",
    "ui design",
    "visual design",
    "color theory",
    "typography",
    "responsive design",
    "mobile design",
    "web design",
    "design system",
    "usability testing",
    "user centered design",
    "prototyping tool",
    "user empathy",
    "affinity diagram",
    "card sorting",
    "accessibility",
    "graphic design",
    "motion design",
    "user engagement",
    "product design",
    "user persona",
    "ui ux",
    "ui",
    "ux",
    "creative process",
    "design thinking",
    "wireframing tool",
    "responsive web design",
])
software_engineer_keywords = set([
    "python",
    "java",
    "javascript",
    "code",
    "algorithm",
    "git",
    "database",
    "framework",
    "debug",
    "backend",
    "frontend",
    "testing",
    "deployment",
    "version control",
    "docker",
    "web",
    "server",
    "programming",
    "ide",
    "performance",
    "rest",
    "library",
    "software",
    "development",
    "agile",
    "security",
    "bug",
    "scripting",
    "automation",
    "software architecture",
    "code review",
    "devops",
    "ci cd",
    "machine learning",
    "api",
    "api documentation",
    "open source",
    "scalability",
    "cloud computing",
    "microservices",
    "framework",
    "full stack",
    "frontend",
    "backend"
])
sensitive_keywords = set([
    "password",
    "user credentials",
    # "login",
    "ssn",
    "credit card",
    "customer info",
    "confidential",
    "private",
    "proprietary",
    "restricted access",
    "sensitive data",
    "classified",
    "work related",
    "internal use only",
    "nda",
    "drug",
    "illegal substance",
    "controlled substance",
    "sex",
    "sexual",
    "explicit content",
    "inappropriate",
    "harassment",
    "discrimination",
    "offensive",
    "violence",
    "threat",
    "bullying",
    "hate speech",
    "racist",
    "sexist",
    "homophobic",
    "threatening language",
    "conflict of interest",
    "insider info",
    "trade secret",
    "financial details",
    "health info",
    "pii",
    "personal info",
    "embarrassing",
    "shameful",
    "regret",
    "secret",
    "unsend",
    "illegal",
    "black market",
    "under the table",
    "dirty money",
    "unethical",
    "scam",
    "fraud",
    "bribe",
    "kickback",
    "money laundering",
    "unauthorized access",
    "backdoor",
    "exploit",
    "vulnerability",
    "compromised",
    "security breach",
    "hack",
    "phishing",
    "malware",
    "spyware",
    "virus",
    "trojan",
    "ransomware",
    "data breach",
    "cyber attack",
    # Add more relevant keywords
])
health_keywords = [
    "health",
    "wellness",
    "physical health",
    "mental health",
    "exercise",
    "nutrition",
    "sleep",
    "stress",
    "self-care",
    "mindfulness",
    "fitness",
    "diet",
    "weight",
    "meditation",
    "therapy",
    "counseling",
    "anxiety",
    "depression",
    "mental well-being",
    "healthy habits",
    "medical",
    "doctor",
    "nutritionist",
    "exercise routine",
    "mental clarity",
    "well-being",
    "emotional health",
    "healthcare",
    "preventive care",
    "health checkup",
    "lifestyle",
    "disease prevention",
    "mental resilience",
    "workout",
    "physical activity",
    "health goal",
    "stress management",
    "holistic health",
    "mind-body connection",
    "hydration",
    "mental wellness",
    "healthcare provider",
    "sleep hygiene",
    "health assessment",
    "healthy living",
    "medical advice",
    # Add more relevant keywords
]
world_knowledge_keywords = [
    "history",
    "politics",
    "physics",
    "science",
    "geography",
    "historical events",
    "political figures",
    "scientific discoveries",
    "world affairs",
    "global events",
    "space exploration",
    "technology advancements",
    "philosophy",
    "sociology",
    "cultural studies",
    "archaeology",
    "economics",
    "government",
    "international relations",
    "scientific theories",
    "cosmology",
    "astronomy",
    "mathematics",
    "scientific research",
    "environmental issues",
    "social issues",
    "philanthropy",
    "research studies",
    "world history",
    "political ideologies",
    "historical figures",
    "scientific experiments",
    "political science",
    "quantum physics",
    "cosmological theories",
    "scientific revolutions",
    "humanities",
    "civics",
    "academic discourse",
    "academic journals",
    "knowledge acquisition",
    "critical thinking",
    "worldview",
    "educational philosophy",
    # Add more relevant keywords
]
culture_keywords = [
    "culture",
    "entertainment",
    "movies",
    "films",
    "television",
    "TV shows",
    "music",
    "genres",
    "artists",
    "albums",
    "songs",
    "literature",
    "books",
    "authors",
    "reading",
    "gaming",
    "video games",
    "board games",
    "sports",
    "art",
    "visual arts",
    "performing arts",
    "theater",
    "dance",
    "photography",
    "pop culture",
    "celebrities",
    "fashion",
    "trends",
    "cuisine",
    "food",
    "culinary arts",
    "travel",
    "adventure",
    "exploration",
    "festivals",
    "cultural events",
    "creative expression",
    "media",
    "entertainment industry",
    "cultural influences",
    "cultural diversity",
    "subcultures",
    "creativity",
    "aesthetics",
    "cultural heritage",
    "cultural appreciation",
    # Add more relevant keywords
]
personal_keywords = [
    "relationships",
    "family",
    "friendships",
    "love",
    "dating",
    "marriage",
    "parenting",
    "personal growth",
    "self-improvement",
    "self-discovery",
    "emotional well-being",
    "communication skills",
    "conflict resolution",
    "career",
    "job",
    "employment",
    "professional development",
    "career growth",
    "career change",
    "work-life balance",
    "hobbies",
    "interests",
    "passions",
    "creative pursuits",
    "recreation",
    "leisure activities",
    "personal projects",
    "goal setting",
    "time management",
    "stress relief",
    "mindfulness",
    "happiness",
    "mental clarity",
    "motivation",
    "achievements",
    "ambitions",
    "self-care",
    "personal relationships",
    "interpersonal skills",
    "personal challenges",
    "life milestones",
    "hobby exploration",
    "personal well-being",
    "identity",
    "personality development",
    "life goals",
    # Add more relevant keywords
]
money_keywords = [
    "money",
    "finance",
    "budgeting",
    "savings",
    "investments",
    "financial planning",
    "income",
    "expenses",
    "budget",
    "credit",
    "debit",
    "banking",
    "savings account",
    "investment portfolio",
    "retirement",
    "wealth",
    "financial goals",
    "financial literacy",
    "credit score",
    "financial advisor",
    "taxes",
    "tax planning",
    "financial independence",
    "money management",
    "investment strategies",
    "personal finance",
    "financial advice",
    "passive income",
    "side hustle",
    "entrepreneurship",
    "business",
    "startup",
    "income streams",
    "financial security",
    "debt",
    "loan",
    "insurance",
    "estate planning",
    "inheritance",
    "financial markets",
    "economic trends",
    "financial education",
    "money mindset",
    "investment opportunities",
    "financial decision-making",
    # Add more relevant keywords
]
